### ISSUE TITLE
Configuration.json missing

### ISSUE THREAD

**Issue by memtech3** [YCSRobotics/GrizzlyTime#17]
**Describe the bug**
Log and configuration files are not generated on linux. Settings seem to persist between application restarts.

**Expected behavior**
I expect a configuration.json file to appear in the directory that I launched grizzly time from.

**Log File**
N/A

**Desktop (please complete the following information):**
- Version 2.3.0 (From releases tab)
- Java 11
- Ubuntu 21.10

**Comment by Daltz333** [comment]
I can't seem to reproduce it. ``config.json`` generates correctly for me. Make sure you are running the jar from the current directory. Otherwise the json can generate in the location where you are currently at in console.

If you are running on system startup, this might mean you need a batch or script relative to the location of the jar that launches the jar so the config file gets placed in the right location.

**Comment by memtech3** [comment]
That fixed it! I was running the application by double clicking on it in my file browser. Could this be added to documentation?
